package ca.uqam.inf2120;

class JamoReplacements {

    static final int JAMOS_LAST_CONSONANT_NUMBER = 27;
    static final int JAMOS_FIRST_CONSONANT_NUMBER = 19;

    static final JamosPhoneticReplacement[][] REPLACEMENTS = new JamosPhoneticReplacement[][] {
        /* 1 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u006B\u031A", "\u006B\u031A"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u014B", ""),
            /* 4 */ new JamosPhoneticReplacement("\u006B\u031A", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006B", "\u006E"),
            /* 7 */ new JamosPhoneticReplacement("\u006B", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement("\u006B", "\u0070"),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006B", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006B\u031A", "")
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006B\u0324", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006B\u0324", "\u0068"),
        },
        /* 3 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006B", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006B", "\u0073"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 4 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u006E", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u006E", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u006E", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006C", "\u006C"),
            /* 7 */ new JamosPhoneticReplacement("\u006E", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006E", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006E", "\u0068")
        },
        /* 5 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006E\u0074\u0255", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006E", "\u0074\u0255"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 6 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006E", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 7 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0074\u031A", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u0074\u031A", "")
        },
        /* 8 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u006C", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u006C", "\u006C"),
            /* 4 */ new JamosPhoneticReplacement("\u006C", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006C", "\u006C"),
            /* 7 */ new JamosPhoneticReplacement("\u006C", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\n027E", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\n027E", "")
        },
        /* 9 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\n006B", "\n0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\n006C", "\u006B"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 10 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006D", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u006D"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 11 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u0070", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u0070"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 12 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006C", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u0073"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 13 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006C", "\u0074\u02B0"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u0074\u02B0"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 14 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u0070\u02B0", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u0070\u02B0"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 15 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006C", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 16 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u006D", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u006D", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u006D", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006D", "\u006E"),
            /* 7 */ new JamosPhoneticReplacement("\u006D", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006D", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006D", "\u0068")
        },
        /* 17 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0070", "\006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u006D", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u0070\u031A", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006D", "\u006E"),
            /* 7 */ new JamosPhoneticReplacement("\u006D", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement("\u0070\u031A", "\u0070\u031A"),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0070\u031A", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u0070\u031A", "")
        },
        /* 18 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u0070\u031A", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0070\u031A", "\u0073"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 19 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0070"),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0073", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u0074\u031A", "")
        },
        /* 20 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u006E", "\u0074\u031A"),
            /* 4 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement("\u0073\u0324", "\u0073"),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0073\u0324", ""),
            /* 13 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u0255\u02B0"),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 21 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u014B", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u014B", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u014B", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006E", ""),
            /* 7 */ new JamosPhoneticReplacement("\u014B", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u014B", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u014B", "\u0068")
        },
        /* 22 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u0255\u02B0"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u0255\u02B0")
        },
        /* 23 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u0255\u02B0"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u0255\u02B0")
        },
        /* 24 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006B\u031A", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement("\u006B\u031A", "\u0074"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006B\u031A", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006B\u031A", "")
        },
        /* 25 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement("\u0074\u031A", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0074\u031A", "\u0074\u0255\u02B0"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u0074\u031A", "")
        },
        /* 26 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0070\u031A", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u0070\u031A", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u0070\u031A", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement("\u0070\u031A", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0070\u031A", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u0070\u031A", "")
        },
        /* 27 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u0068", "\u006B\u031A"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u0068", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u0068", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u027E", ""),
            /* 7 */ new JamosPhoneticReplacement("\u0068", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u0068", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        }
    };
}
