package ca.uqam.inf2120;

class JamoReplacements {

    static final int JAMOS_LAST_CONSONANT_NUMBER = 27;
    static final int JAMOS_FIRST_CONSONANT_NUMBER = 19;

    static final JamosPhoneticReplacement[][] REPLACEMENTS = new JamosPhoneticReplacement[][] {
        /* 1 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u006B\u031A", "\u006B\u031A"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u014B", ""),
            /* 4 */ new JamosPhoneticReplacement("\u006B\u031A", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006B", "\u006E"),
            /* 7 */ new JamosPhoneticReplacement("\u006B", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement("\u006B", "\u0070"),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006B", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006B\u031A", "")
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006B\u0324", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006B\u0324", "\u0068"),
        },
        /* 3 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006B", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006B", "\u0073"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 4 */
        {
            /* 1 */ new JamosPhoneticReplacement("\u006E", "\u006B"),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement("\u006E", "\u006E"),
            /* 4 */ new JamosPhoneticReplacement("\u006E", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement("\u006C", "\u006C"),
            /* 7 */ new JamosPhoneticReplacement("\u006E", "\u006D"),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006E", ""),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement("\u006E", "\u0068")
        },
        /* 5 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006E\u0074\u0255", "\u0074"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006E", "\u0074\u0255"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 6 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement("\u006E", "\u0074\u031A"),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement("\u006C", "\u0068"),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 7 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        },
        /* 2 */
        {
            /* 1 */ new JamosPhoneticReplacement(null, null),
            /* 2 */ new JamosPhoneticReplacement(null, null),
            /* 3 */ new JamosPhoneticReplacement(null, null),
            /* 4 */ new JamosPhoneticReplacement(null, null),
            /* 5 */ new JamosPhoneticReplacement(null, null),
            /* 6 */ new JamosPhoneticReplacement(null, null),
            /* 7 */ new JamosPhoneticReplacement(null, null),
            /* 8 */ new JamosPhoneticReplacement(null, null),
            /* 9 */ new JamosPhoneticReplacement(null, null),
            /* 10 */ new JamosPhoneticReplacement(null, null),
            /* 11 */ new JamosPhoneticReplacement(null, null),
            /* 12 */ new JamosPhoneticReplacement(null, null),
            /* 13 */ new JamosPhoneticReplacement(null, null),
            /* 14 */ new JamosPhoneticReplacement(null, null),
            /* 15 */ new JamosPhoneticReplacement(null, null),
            /* 16 */ new JamosPhoneticReplacement(null, null),
            /* 17 */ new JamosPhoneticReplacement(null, null),
            /* 18 */ new JamosPhoneticReplacement(null, null),
            /* 19 */ new JamosPhoneticReplacement(null, null)
        }
    };
}
